name: Deployment Workflow-2
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Lint Code
        run: |
          pip install flake8
          flake8 .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          python -m unittest discover -s tests
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip        
      - name: Build Project
        run: |
          echo "Building the project..."
          # Add your build commands here
      - name: upload Artifacts
        uses: actions/upload-artifact@latest
        with:
          name: build-artifacts
          path: |
            ./build/
            

  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Get Code
        uses: actions/checkout@v3 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip        
      - name: Deploy Project
        run: |
          echo "Deploying the project..."
          # Add your deployment commands here